[features]
seeds = false
[programs.localnet]
maius_program_library = "5aoQ5SF77E73o8KqfXc2LHMP3yfbwkqPgnd6aAAw1bfJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/github/home/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
